load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "MinStack",
    srcs = ["MinStack.cpp"],
)

cc_binary(
    name = "QueueWithTwoStack",
    srcs = ["QueueWithTwoStack.cpp"],
)

cc_binary(
    name = "CatDogQueue",
    srcs = ["CatDogQueue.cpp"],
)

cc_binary(
    name = "SortByStack",
    srcs = ["SortByStack.cpp"],
)

cc_binary(
    name = "MaxSlideWindow",
    srcs = ["MaxSlideWindow.cpp"],
)

cc_binary(
    name = "GetNearLessNeighbor",
    srcs = ["GetNearLessNeighbor.cpp"],
)


cc_binary(
    name = "MaxSubRecSize",
    srcs = ["MaxSubRecSize.cpp"],
)

cc_binary(
    name = "GetNum",
    srcs = ["GetNum.cpp"],
)