cc_binary(
    name = "PrintCommPart",
    srcs = ["PrintCommPart.cpp"],
)

cc_binary(
    name = "RemoveLastKthNode",
    srcs = ["RemoveLastKthNode.cpp"],
)

cc_binary(
    name = "ReverseList",
    srcs = ["ReverseList.cpp"],
)

cc_binary(
    name = "JosephusKill",
    srcs = ["JosephusKill.cpp"],
)

cc_binary(
    name = "IsPalidromeList",
    srcs = ["IsPalidromeList.cpp"],
)

cc_binary(
    name = "PartitionList",
    srcs = ["PartitionList.cpp"],
)

cc_binary(
    name = "ReverseKNodes",
    srcs = ["ReverseKNodes.cpp"],
)

cc_binary(
    name = "TreeToDoubleList",
    srcs = ["TreeToDoubleList.cpp"],
)

cc_binary(
    name = "MergeIntervals",
    srcs = ["MergeIntervals.cpp"],
)