cc_binary(
    name = "Fib",
    srcs = ["Fib.cpp"],
)

cc_binary(
    name = "MinPathSum",
    srcs = ["MinPathSum.cpp"],
)

cc_binary(
    name = "Walk",
    srcs = ["Walk.cpp"],
)

cc_binary(
    name = "CoinChange",
    srcs = ["CoinChange.cpp"],
)

cc_binary(
    name = "Change",
    srcs = ["Change.cpp"],
)

cc_binary(
    name = "BalloonMaxCoins",
    srcs = ["BalloonMaxCoins.cpp"],
)

cc_binary(
    name = "maxEnvelopes",
    srcs = ["MaxEnvelopes.cpp"],
)
